trigger:
- main

variables:
  location: 'WestEurope'
  bicepFile: './infra/windows-vm.bicep'

pool:
  name: Default  # Your self-hosted Windows agent pool

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Deploy Windows VM Infrastructure'
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      Write-Host "Azure CLI Version:"
      az --version
      
      Write-Host "Creating resource group if needed..."
      az group create --name $(resourceGroupName) --location $(location)
      
      Write-Host "Deploying Windows VM infrastructure..."
      $deploymentName = "windows-vm-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
      
      az deployment group create `
        --resource-group $(resourceGroupName) `
        --template-file $(bicepFile) `
        --parameters "adminUsername=azureuser" `
        --parameters "adminPassword=$(VM_ADMIN_PASSWORD)" `
        --parameters "location=$(location)" `
        --name $deploymentName `
        --verbose
      
      Write-Host "Deployment completed successfully!"
      
      Write-Host "Getting VM public IP..."
      az deployment group show `
        --resource-group $(resourceGroupName) `
        --name $deploymentName `
        --query "properties.outputs.publicIpAddress.value" `
        --output tsv
    workingDirectory: $(Build.SourcesDirectory)
