trigger:
- main

pool: default  # This targets your self-hosted agent

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-connection'  # Must match your service connection name
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      az group create --name test-rg --location westeurope
