trigger: none

variables:
  resourceGroupName: 'saxion-test-rg'
  location: 'WestEurope'
  bicepFile: './infra/main.bicep'
  paramFile: './infra/main.parameters.json'

pool:
  name: Default

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Deploy Resources'
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: |
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create ^
        --resource-group $(resourceGroupName) ^
        --template-file $(bicepFile) ^
        --parameters "@$(paramFile)" ^
        --parameters adminPassword=$(VM_ADMIN_PASSWORD)
  env:
    VM_ADMIN_PASSWORD: $(VM_ADMIN_PASSWORD)
