trigger:
- main

pool: default  # Use your self-hosted agent pool name if it's different

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-connection'  # This must match your service connection name
    scriptType: 'ps'  # Use 'bash' if your agent is Linux
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "📦 Starting Bicep deployment..."
      az deployment sub create \
        --location westeurope \
        --template-file ./main.bicep \
        --parameters environment=dev location=westeurope
      echo "✅ Bicep deployment finished"
