trigger:
- main

variables:
  resourceGroupName: 'saxion-test-rg'
  location: 'WestEurope'
  bicepFile: './infra/main.bicep'
  paramFile: './infra/main.bicepparam'

pool:
  name: Default  # Use your self-hosted agent pool

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Deploy Bicep Template'
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create \
        --resource-group $(resourceGroupName) \
        --template-file $(bicepFile) \
        --parameters @$(paramFile)
