trigger:
- none

variables:
  resourceGroupName: 'winvm-rg'
  location: 'westeurope'
  templateFile: './main.bicep'
  vnetName: 'my-vnet'
  subnetName: 'my-subnet'
  adminUN: 'azureuser' # Username
  # adminPASS must be set as a secret variable in Azure DevOps pipeline

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
    - job: Build
      steps:
        - checkout: self
        - script: |
            echo "Build phase: validating Bicep syntax"
            az bicep build --file $(templateFile)
          displayName: 'Build: Validate and Compile Bicep'

- stage: Test
  jobs:
    - job: Test
      steps:
        - task: AzureCLI@2
          displayName: 'Test: What-if Deployment'
          inputs:
            azureSubscription: 'azure-connection'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az deployment group what-if \
                --resource-group $(resourceGroupName) \
                --template-file $(templateFile) \
                --parameters adminUsername='$(adminUN)' adminPassword='$(adminPASS)' \
                             vnetName='$(vnetName)' subnetName='$(subnetName)'

- stage: Deploy
  jobs:
    - job: Deploy
      steps:
        - task: AzureCLI@2
          displayName: 'Deploy: Create RG and Deploy Bicep'
          inputs:
            azureSubscription: 'azure-connection'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az group create --name $(resourceGroupName) --location $(location)
              az deployment group create \
                --resource-group $(resourceGroupName) \
                --template-file $(templateFile) \
                --parameters adminUsername='$(adminUN)' adminPassword='$(adminPASS)' \
                             vnetName='$(vnetName)' subnetName='$(subnetName)'
