trigger:
- main

variables:
  resourceGroupName: 'saxion-test-rg'
  location: 'WestEurope'
  bicepFile: 'infra/main.bicep'
  paramFile: 'infra/main.bicepparam'

pool:
  name: Default

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Deploy Bicep Infrastructure'
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: pscore  # Use PowerShell Core instead of bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create `
        --resource-group $(resourceGroupName) `
        --template-file $(bicepFile) `
        --parameters @$(paramFile)
    workingDirectory: $(Build.SourcesDirectory)
