trigger:
- none

variables:
  resourceGroupName: 'winvm-rg'
  location: 'westeurope'
  templateFile: 'main.bicep'
  adminUN: 'azureuser'
  adminPASS: '$(adminPassword)' # define this as a secret in your pipeline library
  vnetName: 'my-existing-vnet'
  subnetName: 'default'

stages:
- stage: Deploy
  displayName: Deploy Infrastructure
  jobs:
  - job: DeployInfra
    displayName: Deploy with Bicep
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account set --subscription $(AZURE_SUBSCRIPTION_ID)
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file $(templateFile) \
            --parameters natGatewayName='NatGateway01' \
                         publicIpName='pip-natgw' \
                         vnetName='$(vnetName)' \
                         subnetName='$(subnetName)' \
                         adminUsername='$(adminUN)' \
                         adminPassword='$(adminPASS)'