trigger:
- none

pool: default  # Use your self-hosted agent pool name if it's different

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Starting Bicep deployment..."
      az deployment sub create `
        --location westeurope `
        --template-file ./main.bicep `
        --parameters environment=dev location=westeurope
      Write-Host "Bicep deployment finished"

