trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  vmName: 'myWinVM'
  resourceGroup: 'winvm-rg'
  location: 'West Europe'

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Install Bicep'
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az bicep install

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Bicep Template'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azure-connection'
    subscriptionId: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroup)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: 'vm-deploy.bicep'
    csmParametersFile: 'vm-params.bicepparam'
    deploymentMode: 'Incremental'
