trigger:
- none

variables:
  resourceGroupName: 'juict-test'
  location: 'WestEurope'
  bicepFile: './infra/main.bicep'
  paramFile: './infra/main.parameters.json'

pool:
  name: Default

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Deploy Bicep Infrastructure'
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create `
        --resource-group $(resourceGroupName) `
        --template-file $(bicepFile) `
        --parameters "@$(paramFile)" `
        --parameters "adminPassword=$(adminPassword)" `
        --parameters "adminUsername=azureuser" `
        --parameters "location=$(location)"
    workingDirectory: $(Build.SourcesDirectory)
